[package]
name = "cynic-examples"
version = "0.9.0"
authors = ["Graeme Coupar <grambo@grambo.me.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
github = ["serde_json"]

[dependencies]
cynic = { path = "../cynic" }
cynic-codegen = { path = "../cynic-codegen" }
reqwest = { version = "0.10.1", features = ["json", "blocking"] }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
insta = "0.16.0"
